name: Compile and Test Java Api

on:
  pull_request:
    branches:
      - main

jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh
      - name: Build and Test
        working-directory: .
        run: ./gradlew build test --info --stacktrace
